variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test
  - pages

archlinux-test:
  stage: build
  image: "archlinux:latest"
  before_script:
    - pacman -Syu --noconfirm 
    - pacman -S --noconfirm git hugo neofetch
  script:
    - neofetch
    - hugo new site test && cd test
    - mkdir themes/arwiki
    - cp -r ../archetypes themes/arwiki 
    - cp -r ../data themes/arwiki
    - cp -r ../i18n themes/arwiki
    - cp -r ../layouts themes/arwiki
    - cp ../local_git_config.sh themes/arwiki
    - cp -r ../static themes/arwiki
    - cp -r ../assets themes/arwiki
    - cp -r ../exampleSite themes/arwiki
    - cp -r ../images themes/arwiki
    - ls
    - cp ../theme.toml themes/arwiki
    - rm -rf ../content && cp -r themes/arwiki/exampleSite/content/ . 
    - rm config.toml && cp themes/arwiki/exampleSite/deploy.yaml ./config.yaml 
    - hugo
    - echo "Build on Archlinux Latest successfull!"

test:
  stage: test
  image: registry.gitlab.com/pages/hugo:latest
  script:
    - hugo
  except:
    - master

pages:
  stage: pages
  image: registry.gitlab.com/pages/hugo:latest
  script:
    - hugo new site test && cd test
    - mkdir themes/arwiki 
    - cp -r ../archetypes themes/arwiki 
    - cp -r ../data themes/arwiki
    - cp -r ../i18n themes/arwiki
    - cp -r ../layouts themes/arwiki
    - cp ../local_git_config.sh themes/arwiki
    - cp -r ../static themes/arwiki
    - cp -r ../assets themes/arwiki
    - cp -r ../exampleSite themes/arwiki
    - cp -r ../images themes/arwiki
    - ls
    - rm -rf ../content && cp -r themes/arwiki/exampleSite/content/ . 
    - rm config.toml && cp themes/arwiki/exampleSite/deploy.yaml ./config.yaml
    - hugo
    - mv public ../
  artifacts:
    paths:
      - public
  only:
    - master
