variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test
  - pages

debian-test:
  stage: build
  image: "debian:stable"
  before_script:
    - apt-get update -y
    - apt-get install -y git hugo neofetch
  script:
    - neofetch
    - hugo new site test && cd test
    - mkdir themes/arwiki 
    - cp -r ../archetypes themes/arwiki
    - cp -r ../exampleSite themes/arwiki 
    - cp -r ../layouts themes/arwiki
    - cp ../LICENSE themes/arwiki
    - cp ../README.md themes/arwiki
    - cp -r ../static themes/arwiki
    - cp ../theme.toml themes/arwiki
    - rm -rf ../content && cp -r themes/arwiki/exampleSite/content/ . 
    - rm config.yaml && cp themes/arwiki/exampleSite/deploy.yaml ./config.yaml
    - mkdir static/img && cp themes/arwiki/static/img/logo.png static/img/
    - hugo
    - echo "Build on Debian Stable successfull!"

fedora-test:
  stage: build
  image: "fedora:latest"
  before_script:
    - dnf update -y
    - dnf install -y git hugo neofetch
  script:
    - neofetch
    - hugo new site test && cd test
    - mkdir themes/arwiki 
    - cp -r ../archetypes themes/arwiki
    - cp -r ../exampleSite themes/arwiki 
    - cp -r ../layouts themes/arwiki
    - cp ../LICENSE themes/arwiki
    - cp ../README.md themes/arwiki
    - cp -r ../static themes/arwiki
    - cp ../theme.toml themes/arwiki
    - rm -rf ../content && cp -r themes/arwiki/exampleSite/content/ . 
    - rm config.toml && cp themes/arwiki/exampleSite/deploy.yaml ./config.yaml
    - mkdir static/img && cp themes/arwiki/static/img/logo.png static/img 
    - hugo
    - echo "Build on Fedora Latest successfull!"

archlinux-test:
  stage: build
  image: "archlinux:latest"
  before_script:
    - pacman -Syu --noconfirm 
    - pacman -S --noconfirm git hugo neofetch
  script:
    - neofetch
    - hugo new site test && cd test
    - mkdir themes/arwiki 
    - cp -r ../archetypes themes/arwiki
    - cp -r ../exampleSite themes/arwiki 
    - cp -r ../layouts themes/arwiki
    - cp ../LICENSE themes/arwiki
    - cp ../README.md themes/arwiki
    - cp -r ../static themes/arwiki
    - cp ../theme.toml themes/arwiki
    - rm -rf ../content && cp -r themes/arwiki/exampleSite/content/ . 
    - rm config.toml && cp themes/arwiki/exampleSite/deploy.yaml ./config.yaml 
    - mkdir static/img && cp themes/arwiki/static/img/logo.png static/img    
    - hugo
    - echo "Build on Archlinux Latest successfull!"

test:
  stage: test
  image: registry.gitlab.com/pages/hugo:latest
  script:
    - hugo
  except:
    - master

pages:
  stage: pages
  image: registry.gitlab.com/pages/hugo:latest
  script:
    - hugo new site test && cd test
    - mkdir themes/arwiki 
    - cp -r ../archetypes themes/arwiki
    - cp -r ../exampleSite themes/arwiki 
    - cp -r ../layouts themes/arwiki
    - cp ../LICENSE themes/arwiki
    - cp ../README.md themes/arwiki
    - cp -r ../static themes/arwiki
    - cp ../theme.toml themes/arwiki
    - rm -rf ../content && cp -r themes/arwiki/exampleSite/content/ . 
    - rm config.toml && cp themes/arwiki/exampleSite/deploy.yaml ./config.yaml 
    - mkdir static/img && cp themes/arwiki/static/img/logo.png static/img
    - hugo
    - mv public ../
  artifacts:
    paths:
      - public
  only:
    - master
