name = "Arwiki"
license = "GPL V3"
licenselink = "https://gitlab.com/avron/arwiki/-/blob/master/LICENSE"
description = "An accessibility-friendly Hugo theme, modified, beautified and ported from the original Cupper Hugo theme."
homepage = "https://gitlab.com/avron/arwiki/"
tags = ["accessible", "blog", "documentation", "dark", "wiki"]
features = ["accessible", "blog", "documentation", "dark", "wiki"]
min_version = "0.60.1"

[author]
  name = "Abaraham Raji"
  homepage = "https://abrahamraji.in"

[original]
  name = "Cupper Hugo Theme"
  homepage = "https://cupper-hugo-theme.netlify.com/"
  repo = "https://github.com/zwbetz-gh/cupper-hugo-theme"
